#!/bin/bash

# copy any amazon credential files from this folder to /opt/ampi on the device
# the last one will be selected for use on the device, but this can
# be changed via the bluetooth menu

# To use this file on a provisioning disk, copy it to
#   PATH_TO_USB_TOP_LEVEL_FOLDER/fleetsie/custom_post/setup
# and put at least one file called WHATEVER_amazon_secrets.txt in the
# same folder.

for f in `ls -1 *amazon_secrets.txt`; do
    TARG=/opt/ampi/$f
    cp $f $TARG
    chown ampi:ampi $TARG
done
if [[ "$f" ]]; then
    ln -f -s "$f" /opt/ampi/amazon_secrets.txt
fi
