#!/bin/bash

# handle addition or removal of an audiomoth
#
# called from a udev rule as
#
#    add|remove DEVNO [ RRRR_SERIAL ]
#
# where:
#
#    - DEVNO is the kernel device number, which depends on plugging and
#    enumeration order; this number is needed for referring to the
#    audiomoth in the ALSA framework (e.g. "hw:CARD=2,DEV=0" for DEVNO=2)
#
#    - RRRR is the zero-padded sampling rate, in kHz; e.g. 0032
#
#    - SERIAL is a 16-digit hex serial number for the audiomoth
#
# Note: RRRR_SERIAL is only present if the command is add

# lock to protect against interleaved operation when multiple
# AM detected simultaneously

( flock -x 9 || exit 1 ;

  CMD=$1
  DEVNO=$2
  SERIAL=${3//*_/}

  AM_SHARED_FILE=/opt/ampi/ampi_common
  if [[ ! -f $AM_SHARED_FILE ]]; then
      echo "Can't find shared code file $AM_SHARED_FILE" 1>&2
      exit 100
  fi
  . $AM_SHARED_FILE

  SERIAL_DIR=$AM_DEV_DIR/$SERIAL
  LINK_DEVNO=$AM_DEV_DIR/$DEVNO
  case $CMD in
      add)
	  mkdir -p $SERIAL_DIR
	  chown 1000:1000 $SERIAL_DIR
	  ln -f -s $SERIAL $LINK_DEVNO
	  ln -s $DEVNO $SERIAL_DIR/device_num
	  # indicate device is in a sleep state until Jan 1, 2100
	  ln -s sleep $SERIAL_DIR/state
	  ln -s 4102459200 $SERIAL_DIR/until
	  am_configure
	  systemctl start shiftwrap@ampi-capture@$DEVNO-$SERIAL
	  ;;
      remove)
	  # we don't have serial# so get it from the links
	  SERIAL=`readlink $LINK_DEVNO`
	  # protect against wonkiness
	  if [[ "$SERIAL" == "" ]]; then
	      exit 1
	  fi
	  SERIAL_DIR=$AM_DEV_DIR/$SERIAL
	  systemctl stop shiftwrap@ampi-capture@$DEVNO-$SERIAL
	  rm $LINK_DEVNO
	  rm -rf $SERIAL_DIR
	  ;;
  esac
) 9< $0
